name: Run Python Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 8 * * *'  # Runs daily at 8:30 AM UTC (2:00 PM IST)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run the Python script with necessary environment variables
    - name: Run Python Script
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        GUJARATI_CHAT_ID: ${{ secrets.GUJARATI_CHAT_ID }}
        ENGLISH_CHAT_ID: ${{ secrets.ENGLISH_CHAT_ID }}
        GUJARATI_CHANNEL_ID: ${{ secrets.GUJARATI_CHANNEL_ID }}
        ENGLISH_CHANNEL_ID: ${{ secrets.ENGLISH_CHANNEL_ID }}
      run: |
        python main.py
