name: Python App with Pandoc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure pypandoc is in your requirements.txt
        sudo apt-get install texlive-xetex texlive-lang-indic texlive-fonts-extra
        sudo apt-get install -y fonts-noto-core fonts-lohit-gujr fonts-noto-unhinted  # Install Gujarati fonts


    - name: Run the script
      run: |
        python main.py  # Replace this with the path to your script
